### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by mrjasonn** [supersmartypants/BoostedBrightness#41]
Please update to 1.19.4

**Comment by larryr1** [comment]
I've managed to get the mod working on 1.19.4 by changing the mapping and loader versions in [gradle.properties](https://github.com/adamviola/BoostedBrightness/blob/master/build.gradle) and changing a removed method in [ModMenuIntegration.java](https://github.com/adamviola/BoostedBrightness/blob/7ba68365d52ff9cd7e60daab24014baa1bc577ba/src/main/java/net/boostedbrightness/ui/ModMenuIntegration.java#L41) but it still crashes when opening ModMenu, Other than that, it works. I'm not sure if I should make a pull request or not because it's not fully working and the versions of mappings may have to be changed to fix that error. It might also be my development client having outdated versions but I'm not sure how to upgrade it since it's an IDE plugin.
